/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsyncWatcherArea: typeof import('./src/components/async-watcher-area.vue')['default']
    BaseAlert: typeof import('./src/components/alert/base-alert.vue')['default']
    DangerAlert: typeof import('./src/components/alert/danger-alert.vue')['default']
    EditPokemonPopup: typeof import('./src/components/edit-pokemon-popup.vue')['default']
    GoogleSpreadsheetPopup: typeof import('./src/components/google-spreadsheet-popup.vue')['default']
    NatureInfo: typeof import('./src/components/nature-info.vue')['default']
    PokemonBoxTsvPopup: typeof import('./src/components/pokemon-box-tsv-popup.vue')['default']
    PokemonList: typeof import('./src/components/pokemon-list.vue')['default']
    PopupBase: typeof import('./src/components/popup-base.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectTableDetailPopup: typeof import('./src/components/select-table-detail-popup.vue')['default']
    SelectTablePickupPopup: typeof import('./src/components/select-table-pickup-popup.vue')['default']
    SettingList: typeof import('./src/components/setting-list.vue')['default']
    SimulationTeamPopup: typeof import('./src/components/simulation-team-popup.vue')['default']
    SortableTable: typeof import('./src/components/sortable-table.vue')['default']
    SubSkillLabel: typeof import('./src/components/sub-skill-label.vue')['default']
    ToggleArea: typeof import('./src/components/design/toggle-area.vue')['default']
  }
}
