/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsyncWatcherArea: typeof import('./src/components/util/async-watcher-area.vue')['default']
    BaseAlert: typeof import('./src/components/alert/base-alert.vue')['default']
    CandyIcon: typeof import('./src/components/icon/candy-icon.vue')['default']
    CommonSetting: typeof import('./src/components/common-setting.vue')['default']
    CookingSettingPopup: typeof import('./src/components/cooking-setting-popup.vue')['default']
    DangerAlert: typeof import('./src/components/alert/danger-alert.vue')['default']
    DesignTable: typeof import('./src/components/design-table.vue')['default']
    DetailSettingPopup: typeof import('./src/components/detail-setting-popup.vue')['default']
    EvaluateResult: typeof import('./src/components/page-assist/index/evaluate-result.vue')['default']
    EvaluateTableDetailPopup: typeof import('./src/components/evaluate-table-detail-popup.vue')['default']
    FoodList: typeof import('./src/components/status/food-list.vue')['default']
    GoogleSpreadsheetPopup: typeof import('./src/components/google-spreadsheet-popup.vue')['default']
    HelpButton: typeof import('./src/components/help/help-button.vue')['default']
    HelpPopup: typeof import('./src/components/help/help-popup.vue')['default']
    InputCheckbox: typeof import('./src/components/form/input-checkbox.vue')['default']
    InputNumber: typeof import('./src/components/form/input-number.vue')['default']
    InputRadio: typeof import('./src/components/form/input-radio.vue')['default']
    LvLabel: typeof import('./src/components/status/lv-label.vue')['default']
    NameLabel: typeof import('./src/components/status/name-label.vue')['default']
    NatureInfo: typeof import('./src/components/status/nature-info.vue')['default']
    PokemonBoxTsvPopup: typeof import('./src/components/pokemon-box-tsv-popup.vue')['default']
    PokemonEditPopup: typeof import('./src/components/pokemon-edit-popup.vue')['default']
    PokemonFilterEditor: typeof import('./src/components/filter/pokemon-filter-editor.vue')['default']
    PopupBase: typeof import('./src/components/util/popup-base.vue')['default']
    ResourceEditPopup: typeof import('./src/components/resource-edit-popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingButton: typeof import('./src/components/design/setting-button.vue')['default']
    SettingButtonPopup: typeof import('./src/components/design/setting-button-popup.vue')['default']
    SettingList: typeof import('./src/components/util/setting-list.vue')['default']
    SettingTable: typeof import('./src/components/design/setting-table.vue')['default']
    SkillLvLabel: typeof import('./src/components/status/skill-lv-label.vue')['default']
    SortableTable: typeof import('./src/components/sortable-table.vue')['default']
    SubSkillLabel: typeof import('./src/components/status/sub-skill-label.vue')['default']
    SubSkillLabelList: typeof import('./src/components/status/sub-skill-label-list.vue')['default']
    ToggleArea: typeof import('./src/components/design/toggle-area.vue')['default']
  }
}
